export  const contacts = [
    { name: 'Alice', key: 'A' },
    { name: 'Adam', key: 'A' },
    { name: 'Adarsh', key: 'A' },
    { name: 'Aditi', key: 'A' },
    { name: 'Ameesha', key: 'A' },
    { name: 'Ben', key: 'B' },
    { name: 'Bob', key: 'B' },
    { name: 'Bharat', key: 'B' },
    { name: 'Calvin', key: 'C' },
    { name: 'Chahat', key: 'C' },
    { name: 'Daniel', key: 'D' },
    { name: 'Deepak', key: 'D' },
    { name: 'Elizabeth', key: 'E' },
    { name: 'Emly', key: 'E' },
    { name: 'Edwin', key: 'E' },
    { name: 'Falak', key: 'F' },
    { name: 'Falguni', key: 'F' },
    { name: 'Garima', key: 'G' },
    { name: 'Gaurav', key: 'G' },
    { name: 'Harry', key: 'H' },
    { name: 'Harish', key: 'H' },
    { name: 'Harsh', key: 'H' },
    { name: 'Indu', key: 'I' },
    { name: 'Inderjeet', key: 'I' },
    { name: 'Ichaa', key: 'I' },
    { name: 'Inder', key: 'I' },
    { name: 'Jerry', key: 'J' },
    { name: 'Jack', key: 'J' },
    { name: 'Karry', key: 'K' },
    { name: 'Kavita', key: 'K' },
    { name: 'Kiran', key: 'K' },
    { name: 'Lalit', key: 'L' },
    { name: 'Levis', key: 'L' },
    { name: 'Maddy', key: 'M' },
    { name: 'Mansi', key: 'M' },
    { name: 'Mamta', key: 'M' },
    { name: 'Neha', key: 'N' },
    { name: 'Neelu', key: 'N' },
    { name: 'Neeraj', key: 'N' },
    { name: 'Nikhil', key: 'N' },
    { name: 'Om', key: 'O' },
    { name: 'Oliver', key: 'O' },
    { name: 'Pankaj', key: 'P' },
    { name: 'Parkash', key: 'P' },
    { name: 'Pawan', key: 'P' },
    { name: 'Parmod', key: 'P' },
    { name: 'Poonam', key: 'P' },
    { name: 'Priyanka', key: 'P' },
    { name: 'Qalam', key: 'Q' },
    { name: 'Qabil', key: 'Q' }, 
    { name: 'Rahul', key: 'R' },
    { name: 'Rohit', key: 'R' },
    { name: 'Raj', key: 'R' },
    { name: 'Ram', key: 'R' },
    { name: 'Simran', key: 'S' },
    { name: 'Sachin', key: 'S' },
    { name: 'Sagar', key: 'S' },
    { name: 'Sahil', key: 'S' },
    { name: 'Tarun', key: 'T' },
    { name: 'Tom', key: 'T' },
    { name: 'Uday', key: 'U' },
    { name: 'Udit', key: 'U' },
    { name: 'Urvashi', key: 'U' },
    { name: 'Vishal', key: 'V' },
    { name: 'Vasu', key: 'V' },
    { name: 'Vanshika', key: 'V' },
    { name: 'Vikas', key: 'V' },
    { name: 'Wasim', key: 'W' },
    { name: 'Xama', key: 'X'},
    { name: 'Yogita', key: 'Y' },
    { name: 'Yogesh', key: 'Y' },
    { name: 'Zafar', key: 'Z' },
    { name: 'Zoya', key: 'Z' },
  ];


export const sections = [
    { title: 'A', data: contacts.filter(contact => contact.key === 'A') },
    { title: 'B', data: contacts.filter(contact => contact.key === 'B') },
    { title: 'C', data: contacts.filter(contact => contact.key === 'C') },
    { title: 'D', data: contacts.filter(contact => contact.key === 'D') },
    { title: 'E', data: contacts.filter(contact => contact.key === 'E') },
    { title: 'F', data: contacts.filter(contact => contact.key === 'F') },
    { title: 'G', data: contacts.filter(contact => contact.key === 'G') },
    { title: 'H', data: contacts.filter(contact => contact.key === 'H') },
    { title: 'I', data: contacts.filter(contact => contact.key === 'I') },
    { title: 'J', data: contacts.filter(contact => contact.key === 'J') },
    { title: 'K', data: contacts.filter(contact => contact.key === 'K') },
    { title: 'L', data: contacts.filter(contact => contact.key === 'L') },
    { title: 'M', data: contacts.filter(contact => contact.key === 'M') },
    { title: 'N', data: contacts.filter(contact => contact.key === 'N') },
    { title: 'O', data: contacts.filter(contact => contact.key === 'O') },
    { title: 'P', data: contacts.filter(contact => contact.key === 'P') },
    { title: 'Q', data: contacts.filter(contact => contact.key === 'Q') },
    { title: 'R', data: contacts.filter(contact => contact.key === 'R') },
    { title: 'S', data: contacts.filter(contact => contact.key === 'S') },
    { title: 'T', data: contacts.filter(contact => contact.key === 'T') },
    { title: 'U', data: contacts.filter(contact => contact.key === 'U') },
    { title: 'V', data: contacts.filter(contact => contact.key === 'V') },
    { title: 'W', data: contacts.filter(contact => contact.key === 'W') },
    { title: 'X', data: contacts.filter(contact => contact.key === 'X') },
    { title: 'Y', data: contacts.filter(contact => contact.key === 'Y') },
    { title: 'Z', data: contacts.filter(contact => contact.key === 'Z') },
  ];  